[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "pytessim"
version = "0.1.0"
description = "Waveform fitting utilities"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    {name = "William Matava"}
]

dependencies = [
    "numpy",
    "detprocess",
    "pytesdaq",
    "pytesio"
]

[tool.setuptools.packages.find]
include = ["pytessim*"]
